baseURL: 'https://example.com'
languageCode: 'en-us'
title: 'Mostly Harmless'
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
paginate: 6
social:
  twitter: '#'
  github: '#'
  instagram: '#'
  linkedin: '#'
  dribbble: '#'
  youtube: '#'
taxonomies:
  author: authors
